# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='shell_file',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u811a\u672c\u8def\u5f84'),
        ),
    ]
