# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_rsync_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='source_auth',
            field=models.BooleanField(default=False, verbose_name='\u6e90\u7801\u8ba4\u8bc1'),
        ),
    ]
