# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_host_account'),
        ('delivery', '0003_delivery_source_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='serverList',
            field=models.ManyToManyField(blank=True, to='cmdb.Host', verbose_name='\u6240\u5728\u670d\u52a1\u5668'),
        ),
    ]
