# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='navi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('img', models.CharField(max_length=50, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
