# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-10 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navi',
            old_name='img',
            new_name='description',
        ),
    ]
