# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='java_script',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u542f\u52a8/\u505c\u6b62\u811a\u672c'),
        ),
        migrations.AddField(
            model_name='project',
            name='lvs_cofnig_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8d1f\u8f7d\u5747\u8861\u914d\u7f6e\u6587\u4ef6\u76ee\u5f55'),
        ),
        migrations.AddField(
            model_name='project',
            name='lvs_host_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d1f\u8f7d\u5747\u8861\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='project',
            name='lvs_type',
            field=models.CharField(blank=True, choices=[('nginx', 'nginx'), ('haproxy', 'haproxy')], max_length=50, verbose_name='\u8d1f\u8f7d\u5747\u8861\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='project',
            name='raync_exclude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6392\u9664\u540c\u6b65\u6587\u4ef6\u540d'),
        ),
    ]
