# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0002_authinfo_deploy_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='serverList',
        ),
    ]
