# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=30)),
                ('cpu_model', models.CharField(max_length=30)),
                ('cpu_num', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('sn', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField()),
                ('identity', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(to='cmdb.Host')),
            ],
        ),
    ]
