# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipaddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(max_length=30)),
                ('mask', models.CharField(max_length=30)),
            ],
        ),
    ]
