# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0003_remove_project_serverlist'),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.AuthInfo', verbose_name='\u8d26\u53f7\u4fe1\u606f'),
        ),
    ]
