# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='contact_phone',
            field=models.CharField(max_length=30, null=True, verbose_name='\u79fb\u52a8\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.CharField(max_length=30, null=True, verbose_name='\u8bbe\u5907\u7ec4'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='\u673a\u623f\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='contact',
            field=models.CharField(max_length=30, null=True, verbose_name='\u5ba2\u6237\u7ecf\u7406'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='tel',
            field=models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u7535\u8bdd'),
        ),
    ]
