# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.IntegerField(blank=True, choices=[(1, '\u7269\u7406\u673a'), (2, '\u865a\u62df\u673a'), (3, '\u5bb9\u5668'), (4, '\u7f51\u7edc\u8bbe\u5907'), (5, '\u5176\u4ed6')], null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bbe\u5907\u5382\u5546'),
        ),
    ]
