# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170221_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '\u4f7f\u7528\u4e2d'), (2, '\u672a\u4f7f\u7528'), (3, '\u7ef4\u4fee\u4e2d'), (3, '\u5176\u5b83')], null=True, verbose_name='\u8bbe\u5907\u72b6\u6001'),
        ),
    ]
