# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170216_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='bandwidth',
            field=models.CharField(max_length=30, null=True, verbose_name='\u63a5\u5165\u5e26\u5bbd'),
        ),
        migrations.AddField(
            model_name='idc',
            name='jigui',
            field=models.CharField(max_length=30, null=True, verbose_name='\u673a\u67dc\u4fe1\u606f'),
        ),
    ]
