# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170221_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(blank=True, choices=[(1, '\u7269\u7406\u673a'), (2, '\u865a\u62df\u673a'), (3, '\u5bb9\u5668'), (4, '\u7f51\u7edc\u8bbe\u5907'), (5, '\u5176\u4ed6')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, choices=[(1, '\u4f7f\u7528\u4e2d'), (2, '\u672a\u4f7f\u7528'), (3, '\u7ef4\u4fee\u4e2d'), (3, '\u5176\u5b83')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u72b6\u6001'),
        ),
    ]
