# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_idc_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Idc'),
            preserve_default=False,
        ),
    ]
