# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_idc_ip_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_type',
            field=models.CharField(default='\u865a\u62df\u673a', max_length=50, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='host',
            name='memo',
            field=models.TextField(default='None', max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='host',
            name='other_ip',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='IP\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='host',
            name='position',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='\u6240\u5728\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d'),
        ),
    ]
