# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20170218_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u786c\u76d8\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8bbe\u5907\u7ec4'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.CharField(blank=True, default='\u865a\u62df\u673a', max_length=50, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Idc', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='host',
            name='other_ip',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='\u5176\u5b83IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6240\u5728\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=60, verbose_name='SN\u53f7 \u7801'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vendor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8bbe\u5907\u5382\u5546'),
        ),
    ]
