# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20170218_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='\u7ba1\u7406IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='other_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5176\u5b83IP'),
        ),
    ]
