# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Idc', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
        migrations.AlterField(
            model_name='host',
            name='identity',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='product',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
