# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20170218_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU\u6570\u91cf'),
        ),
    ]
