# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20170218_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='members',
            field=models.ManyToManyField(to='cmdb.Host', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u7ec4\u540d'),
        ),
    ]
