# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20170128_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '\u6570\u636e\u4e2d\u5fc3', 'verbose_name_plural': '\u6570\u636e\u4e2d\u5fc3'},
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(max_length=50, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
